# Generated by Django 5.0.7 on 2024-08-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=30)),
                ('receiver', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('nickname', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=60)),
                ('street', models.CharField(max_length=40)),
                ('number', models.IntegerField()),
                ('level', models.IntegerField()),
                ('door', models.CharField(max_length=2)),
                ('cp_code', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=30)),
                ('telefono', models.CharField(default='0000000', max_length=9)),
                ('mail', models.EmailField(default='mail@address.com', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('won', models.IntegerField()),
                ('lost', models.IntegerField()),
            ],
        ),
    ]
