# Generated by Django 5.0.7 on 2024-08-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadores',
            name='telefono',
            field=models.CharField(default='0000000', max_length=9),
        ),
    ]
